### ISSUE TITLE
`ModuleNotFoundError: No module named 'future'`

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/FIDS#1]
I am getting this error when importing `fids.fids`: 
```
File "fids/fids.py", line 6, in <module>
    from future import __annotations__  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'future'
```

I have only seen people importing `from __future__ import annotations` (i.e., underscores around `future`, not `annotations`). Is this just a typo or is it somehow related to an actual [`future` module](https://pypi.org/project/future/)?

**Comment by michellewang** [comment]
@Remi-Gau

**Comment by jbpoline** [comment]
stackoverflow says `pip3 install future` - or `pip3  install -U future` - that wasn't the issue?

**Comment by Remi-Gau** [comment]
Totally a typo.
Also realizing that I am not even sure the code in here is functional.
Do you need something that generates basic bids and fmriprep datasets?
If so then may be quicker to rely on nilearn internal functions.

**Comment by Remi-Gau** [comment]
@michellewang things should be fixed now
added a smoke test to make sure the basic thing runs

there is a lot to add in here but if you don't need flexibility in terms of subject and session labels, then nilearn internals can get you pretty far.

would probably be good to have a mini-pacakge outside of nilearn that can generate whole bunch of fake bids data fairly flexibly: I know the BIDS maintainers are interested in having something like this.

in any case, let me know if this works for you: if so close the issue otherwise let me know how I can help

**Comment by michellewang** [comment]
@Remi-Gau it works great, thanks!
